# -*- coding: utf-8 -*-
"""simple linear regresson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKF5AcBy0CNDNAQKFinN8tBFe5DXy5Kz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Load the dataset
df = pd.read_csv(r'D:\Internship\linear regression\Breast_cancer_dataset (1).csv', encoding = "latin1")

# Display basic information about the dataset
print("Dataset shape:", df.shape)
print("\nFirst few rows:")
print(df.head())
print("\nColumn names:")
print(df.columns.tolist())

# For simple linear regression, let's use 'radius_mean' as feature (X) and 'area_mean' as target (y)
# These are likely to have a strong linear relationship
X = df[['radius_mean']].values  # Feature matrix (2D array)
y = df['area_mean'].values      # Target vector

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Model evaluation
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\n" + "="*50)
print("SIMPLE LINEAR REGRESSION RESULTS")
print("="*50)
print(f"Feature: radius_mean")
print(f"Target: area_mean")
print(f"Training samples: {X_train.shape[0]}")
print(f"Testing samples: {X_test.shape[0]}")
print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared Score: {r2:.4f}")
print(f"Coefficient (slope): {model.coef_[0]:.4f}")
print(f"Intercept: {model.intercept_:.4f}")

# Manual prediction equation
print(f"\nRegression Equation: area_mean = {model.intercept_:.4f} + {model.coef_[0]:.4f} * radius_mean")

# Visualization
plt.figure(figsize=(12, 5))

# Plot 1: Training data with regression line
plt.subplot(1, 2, 1)
plt.scatter(X_train, y_train, color='blue', alpha=0.6, label='Training Data')
plt.plot(X_train, model.predict(X_train), color='red', linewidth=2, label='Regression Line')
plt.xlabel('Radius Mean')
plt.ylabel('Area Mean')
plt.title('Training Data: Radius vs Area')
plt.legend()
plt.grid(True, alpha=0.3)

# Plot 2: Test data with predictions
plt.subplot(1, 2, 2)
plt.scatter(X_test, y_test, color='green', alpha=0.6, label='Actual Test Data')
plt.scatter(X_test, y_pred, color='red', alpha=0.6, label='Predicted')
plt.xlabel('Radius Mean')
plt.ylabel('Area Mean')
plt.title('Test Data: Actual vs Predicted')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Additional analysis: Let's try different feature combinations
print("\n" + "="*50)
print("COMPARING DIFFERENT FEATURES")
print("="*50)

# Test multiple features to see which has the best linear relationship
features_to_test = ['radius_mean', 'perimeter_mean', 'texture_mean', 'smoothness_mean']
target = 'area_mean'

for feature in features_to_test:
    X_temp = df[[feature]].values
    y_temp = df[target].values

    X_train_temp, X_test_temp, y_train_temp, y_test_temp = train_test_split(
        X_temp, y_temp, test_size=0.2, random_state=42
    )

    model_temp = LinearRegression()
    model_temp.fit(X_train_temp, y_train_temp)
    y_pred_temp = model_temp.predict(X_test_temp)

    r2_temp = r2_score(y_test_temp, y_pred_temp)
    print(f"Feature: {feature:15} -> R-squared: {r2_temp:.4f}")

# Residual analysis
residuals = y_test - y_pred

plt.figure(figsize=(15, 4))

# Plot 1: Residuals vs Predicted values
plt.subplot(1, 3, 1)
plt.scatter(y_pred, residuals, alpha=0.6)
plt.axhline(y=0, color='red', linestyle='--')
plt.xlabel('Predicted Values')
plt.ylabel('Residuals')
plt.title('Residuals vs Predicted Values')
plt.grid(True, alpha=0.3)

# Plot 2: Histogram of residuals
plt.subplot(1, 3, 2)
plt.hist(residuals, bins=30, alpha=0.7, edgecolor='black')
plt.xlabel('Residuals')
plt.ylabel('Frequency')
plt.title('Distribution of Residuals')
plt.grid(True, alpha=0.3)

# Plot 3: Q-Q plot for normality check
plt.subplot(1, 3, 3)
from scipy import stats
stats.probplot(residuals, dist="norm", plot=plt)
plt.title('Q-Q Plot for Normality Check')

plt.tight_layout()
plt.show()

# Example prediction for new data
print("\n" + "="*50)
print("EXAMPLE PREDICTIONS")
print("="*50)

# Predict for some example radius values
example_radii = np.array([[10], [15], [20], [25]]).reshape(-1, 1)
predicted_areas = model.predict(example_radii)

for radius, area in zip(example_radii.flatten(), predicted_areas):
    print(f"Radius: {radius:5.1f} -> Predicted Area: {area:7.1f}")

print("\nModel interpretation:")
print(f"- For each 1 unit increase in radius_mean, area_mean increases by {model.coef_[0]:.2f} units")
print(f"- The R-squared of {r2:.4f} indicates that {r2*100:.2f}% of the variance in area_mean can be explained by radius_mean")
# Polynomial regression comparison (radius_mean -> area_mean)
# Since area scales with radius^2, a degree-2 polynomial should fit better
# than the simple linear model above.
print("\n" + "="*50)
print("POLYNOMIAL REGRESSION COMPARISON")
print("="*50)

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

poly_model = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())
poly_model.fit(X_train, y_train)
y_pred_poly = poly_model.predict(X_test)

mse_poly = mean_squared_error(y_test, y_pred_poly)
r2_poly = r2_score(y_test, y_pred_poly)

print(f"Linear Model      -> MSE: {mse:.2f}, R-squared: {r2:.4f}")
print(f"Polynomial (deg=2) -> MSE: {mse_poly:.2f}, R-squared: {r2_poly:.4f}")

improvement = ((r2_poly - r2) / r2) * 100
print(f"\nR-squared improvement with polynomial model: {improvement:.2f}%")

# Visualization: linear vs polynomial fit
plt.figure(figsize=(8, 5))
sort_idx = X_test[:, 0].argsort()
X_test_sorted = X_test[sort_idx]

plt.scatter(X_test, y_test, color='green', alpha=0.5, label='Actual Test Data')
plt.plot(X_test_sorted, model.predict(X_test_sorted), color='red',
         linewidth=2, label=f'Linear (R2={r2:.3f})')
plt.plot(X_test_sorted, poly_model.predict(X_test_sorted), color='purple',
         linewidth=2, label=f'Polynomial deg=2 (R2={r2_poly:.3f})')
plt.xlabel('Radius Mean')
plt.ylabel('Area Mean')
plt.title('Linear vs Polynomial Regression: Radius vs Area')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()